name: Klavreströms kodmanufaktur
description: Posts about my projects and coding things learnt the hard way.
url: http://www.klavrekod.se
author: Peter Liljenberg

encoding: "utf-8"
timezone: "Europe/Stockholm"

permalink: "/:categories/:year/:month/:title/"

exclude:
  - src
  - CNAME
  - Gemfile
  - Gemfile.lock

gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Peter Liljenberg"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
