encoding: "utf-8"
timezone: "Europe/Stockholm"

permalink: "/:categories/:year/:month/:title/"

exclude:
  - src
  - CNAME
  - Gemfile
  - Gemfile.lock

gems:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Peter Liljenberg"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
